### ISSUE TITLE
THANK YOU.

### ISSUE THREAD

**Issue by denysvitali** [Magisk-Modules-Repo/bacon-mic-fix#1]
Just wanted to say that this fix really helped with my microphone-nightmare I was having since day one on my Nexus 6P.  
You may want to rename this to "mic-fix" or include "Nexus 6P" in the description since it really could help many other people.

I can't thank you enough, really. I RMA'd my phone at least 4 times, and this was the only thing that fixed my problem - completely.

THANK YOU!

**Comment by Nomelas** [comment]
Interesting. This is good news! Thanks for the feedback.
