### ISSUE TITLE
Processing error when downloading with MagiskManager

### ISSUE THREAD

**Issue by Shadowghost** [Magisk-Modules-Repo/bacon-mic-fix#3]
Titel should be sufficient as description. I'm not sure if this is a bug of the manager itself or not. Matlog shows "path appears to be invalid: /storage/emulated/0/MagiskManager/zipname.zip". The paths exists and there is enough free space. I'm on OPO, latest Magisk v11.6 and latest MagiskManager. If you need anything specific, just tell me.

**Comment by Nomelas** [comment]
Hi, this is due to the fact that when you download via github, it adds a directory in the zip. You can install the module through the Magisk Manager app. Or remove the topmost directory from the zip (bacon-mic-fix-master).

Let me know how it goes.

**Comment by Shadowghost** [comment]
Interesting that downloading it inside MagiskManager and afterwards installing it works. That shouldn't be the case :D other modules do work directly BTW.
